name: Build and Minify

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the production build (minification)
      - name: Run build
        run: npm run build

      # Step 5: Deploy or commit the minified files
      - name: Commit and push minified files
        run: |
          git config --global user.name "GinaHorch"
          git config --global user.email "reggiaus@hotmail.com"
          git add dist/style.min.css dist/script.min.js
          git commit -m "Updated minified CSS/JS"
          git push
