name: Build and Minify

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the production build (minification)
      - name: Run build
        run: npm run build

      # Step 5: Deploy or commit the minified files
      - name: Commit and Push changes to GitHub
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git add .
          git commit -m "Updated minified CSS/JS"
          git push https://x-access-token:${{ secrets.GH_PERSONALACCESSTOKENPAT }}@github.com/GinaHorch/GinaHorch.github.io.git HEAD:main
